apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
  namespace: cert-manager
spec:
  isCA: true
  secretName: ca-root 
  issuerRef:
    name: ca-bootstrap
    kind: ClusterIssuer
  commonName: ca-root
  privateKey:
    algorithm: RSA
    size: 2048
